// <auto-generated />
using System;
using System.Collections.Generic;
using DataShapes.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataShapes.Migrations
{
    [DbContext(typeof(DataShapeContext))]
    [Migration("20230804211131_TargetDb.1")]
    partial class TargetDb1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataShapes.Model.Accreditation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccredidationCode")
                        .HasColumnType("text");

                    b.Property<string>("AccredidationName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Accreditation");
                });

            modelBuilder.Entity("DataShapes.Model.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address1")
                        .HasColumnType("text");

                    b.Property<string>("Address2")
                        .HasColumnType("text");

                    b.Property<string>("Address3")
                        .HasColumnType("text");

                    b.Property<int>("AddressType")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<string>("HL7AddressCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<Guid?>("PractitionerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StopDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Use")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PractitionerId");

                    b.HasIndex("TenantId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("DataShapes.Model.Code", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CodingSystem")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("DiagnosisId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EncounterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisId");

                    b.HasIndex("EncounterId");

                    b.ToTable("Codes");
                });

            modelBuilder.Entity("DataShapes.Model.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NameId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("LocationId");

                    b.HasIndex("NameId");

                    b.HasIndex("TenantId");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("DataShapes.Model.ContactMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EmailId")
                        .HasColumnType("uuid");

                    b.Property<string>("IM")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PhoneId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PractitionerId")
                        .HasColumnType("uuid");

                    b.Property<Dictionary<string, string>>("SocialMedia")
                        .IsRequired()
                        .HasColumnType("hstore");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("EmailId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PhoneId");

                    b.HasIndex("PractitionerId");

                    b.HasIndex("TenantId");

                    b.ToTable("ContactMethod");
                });

            modelBuilder.Entity("DataShapes.Model.Diagnosis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrentLocation")
                        .HasColumnType("uuid");

                    b.Property<string>("DiagnosisName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StopDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("DataShapes.Model.DoseDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DoseScheduleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ThisDoseDay")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TreatmentId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DoseScheduleId");

                    b.HasIndex("TreatmentId");

                    b.ToTable("DoseDay");
                });

            modelBuilder.Entity("DataShapes.Model.DoseEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DoseDayId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DoseScheduleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Instruction")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MaxmumCount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinmumCountOrDefault")
                        .HasColumnType("numeric");

                    b.Property<string>("Observation")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("interval");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DoseDayId");

                    b.HasIndex("DoseScheduleId");

                    b.ToTable("DoseEvent");
                });

            modelBuilder.Entity("DataShapes.Model.DoseSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AlternatingRepeatDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DoseRepeatPattern")
                        .HasColumnType("text");

                    b.Property<string>("DoseScheduleName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrn")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("DoseSchedule");
                });

            modelBuilder.Entity("DataShapes.Model.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Email");
                });

            modelBuilder.Entity("DataShapes.Model.Encounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("EncounterIdString")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<string>>("EncounterReasonString")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PrescriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StopDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TreatmentId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionId");

                    b.HasIndex("TreatmentId");

                    b.ToTable("Encounters");
                });

            modelBuilder.Entity("DataShapes.Model.Identifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdSource")
                        .HasColumnType("text");

                    b.Property<string>("IdType")
                        .HasColumnType("text");

                    b.Property<string>("IdUse")
                        .HasColumnType("text");

                    b.Property<string>("IdValue")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PractitionerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StopDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PractitionerId");

                    b.ToTable("Identifier");
                });

            modelBuilder.Entity("DataShapes.Model.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("DiagnosisId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EncounterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, string>>("Licenses")
                        .HasColumnType("hstore");

                    b.Property<int?>("LocationType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PractitionerId")
                        .HasColumnType("uuid");

                    b.Property<int>("StarRating")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisId");

                    b.HasIndex("EncounterId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PractitionerId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("DataShapes.Model.Medication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BrandName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Form")
                        .HasColumnType("text");

                    b.Property<string>("GenericName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGeneric")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOtc")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LongVisualDescription")
                        .HasColumnType("text");

                    b.Property<string>("LotId")
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("MedicationCode")
                        .HasColumnType("text");

                    b.Property<Guid>("MedicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Route")
                        .HasColumnType("text");

                    b.Property<string>("Schedule")
                        .HasColumnType("text");

                    b.Property<string>("ShortVisualDescription")
                        .HasColumnType("text");

                    b.Property<string>("SpecialInstructions")
                        .HasColumnType("text");

                    b.Property<string>("Strength")
                        .HasColumnType("text");

                    b.Property<string>("StrengthUnits")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("DataShapes.Model.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DiagnosisId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoteId")
                        .HasColumnType("text");

                    b.Property<int>("NoteType")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisId");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("DataShapes.Model.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DiagnosisId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EncounterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PractitionerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StopDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisId");

                    b.HasIndex("EncounterId");

                    b.HasIndex("PatientId");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("DataShapes.Model.ObservationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BodySiteId")
                        .HasColumnType("uuid");

                    b.Property<string>("BodyStructure")
                        .HasColumnType("text");

                    b.Property<Guid>("CodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<List<string>>("Interpretation")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MethodId")
                        .HasColumnType("uuid");

                    b.Property<List<string>>("Notes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid?>("ObservationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ObservationReference")
                        .HasColumnType("uuid");

                    b.Property<int?>("ObservationType")
                        .HasColumnType("integer");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SpecimenId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BodySiteId");

                    b.HasIndex("CodeId");

                    b.HasIndex("MethodId");

                    b.HasIndex("ObservationId");

                    b.HasIndex("SpecimenId");

                    b.ToTable("ObservationItem");
                });

            modelBuilder.Entity("DataShapes.Model.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<string>>("Accounts")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("AdmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AlternatePatientIdString")
                        .HasColumnType("text");

                    b.Property<string>("Bed")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DeceasedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DischargeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EncounterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Floor")
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeceased")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("NameId")
                        .HasColumnType("uuid");

                    b.Property<string>("NursingStation")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientCareId")
                        .HasColumnType("uuid");

                    b.Property<string>("PatientClass")
                        .HasColumnType("text");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea");

                    b.Property<string>("PrimaryPatientIdString")
                        .HasColumnType("text");

                    b.Property<string>("Room")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("UsePatientInfo")
                        .HasColumnType("boolean");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId");

                    b.HasIndex("NameId");

                    b.HasIndex("PatientCareId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("DataShapes.Model.PatientCare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlternateGroupId")
                        .HasColumnType("text");

                    b.Property<string>("AlternateInsuranceName")
                        .HasColumnType("text");

                    b.Property<string>("AlternatePolicyId")
                        .HasColumnType("text");

                    b.Property<string>("CareId")
                        .HasColumnType("text");

                    b.Property<byte>("CodeStatus")
                        .HasColumnType("smallint");

                    b.Property<byte>("CodeStatusLimitedCodeOptions")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HipaaChangeAuthorLogin")
                        .HasColumnType("text");

                    b.Property<DateTime>("HipaaChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HipaaDataTransmitAuthentication")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MedicaidId")
                        .HasColumnType("text");

                    b.Property<string>("MedicareId")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrimaryGroupId")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryInsuranceName")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryPolicyId")
                        .HasColumnType("text");

                    b.Property<string>("SocialSecurityNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("PatientCare");
                });

            modelBuilder.Entity("DataShapes.Model.PatientPractitioner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PractitionerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Relationship")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StopDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PractitionerId");

                    b.ToTable("PatientPractitioner");
                });

            modelBuilder.Entity("DataShapes.Model.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CVV2")
                        .HasColumnType("text");

                    b.Property<string>("CardNumber")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("PaymentType")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("PaymentMethod");
                });

            modelBuilder.Entity("DataShapes.Model.PersonName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FamilyName")
                        .HasColumnType("text");

                    b.Property<List<string>>("GivenName")
                        .HasColumnType("text[]");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("KnownByName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PractitionerId")
                        .HasColumnType("uuid");

                    b.Property<List<string>>("Prefix")
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StopDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("Suffix")
                        .HasColumnType("text[]");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PractitionerId");

                    b.ToTable("PersonName");
                });

            modelBuilder.Entity("DataShapes.Model.Phone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Extension")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Phone");
                });

            modelBuilder.Entity("DataShapes.Model.Practitioner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DeceasedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DiagnosisId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EncounterId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EncounterId1")
                        .HasColumnType("uuid");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeceased")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, string>>("LicensesAndQualifications")
                        .IsRequired()
                        .HasColumnType("hstore");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PractitionerIdentifier")
                        .HasColumnType("text");

                    b.Property<int>("PractitionerType")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryLanguage")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisId");

                    b.HasIndex("EncounterId");

                    b.HasIndex("EncounterId1");

                    b.ToTable("Practitioners");
                });

            modelBuilder.Entity("DataShapes.Model.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Catagory")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DcDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DiagnosisId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DispenseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DoNotPerform")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("DoseScheduleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FillingPharmacyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Intent")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsIsolated")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaximumRefills")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MedicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PractitionerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrescriptionName")
                        .HasColumnType("text");

                    b.Property<string>("PriorPrescriptionName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RefillRequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RefillRequestType")
                        .HasColumnType("integer");

                    b.Property<int>("RemainingRefills")
                        .HasColumnType("integer");

                    b.Property<int>("RxType")
                        .HasColumnType("integer");

                    b.Property<int>("ScripStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Sig")
                        .HasColumnType("text");

                    b.Property<List<string>>("SpecialInstructions")
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StatusReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StopDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("WrittenDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WrittenQuantity")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisId");

                    b.HasIndex("DoseScheduleId");

                    b.HasIndex("FillingPharmacyId");

                    b.HasIndex("MedicationId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PractitionerId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("DataShapes.Model.Specimen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateCollected")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeatureDescription")
                        .HasColumnType("text");

                    b.Property<Guid?>("FeatureId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<List<string>>("Request")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SpecimenTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("RoleId");

                    b.HasIndex("SpecimenTypeId");

                    b.ToTable("Specimen");
                });

            modelBuilder.Entity("DataShapes.Model.SpokenLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Fluency")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Locale")
                        .HasColumnType("text");

                    b.Property<string>("NativeLanguageName")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UsEnglishLanguageName")
                        .HasColumnType("text");

                    b.Property<int>("Use")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("SpokenLanguage");
                });

            modelBuilder.Entity("DataShapes.Model.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManagerName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Team")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkGroup")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("DataShapes.Model.Treatment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DcDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DiagnosisId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DispenseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DoseScheduleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("LongDescription")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PractitionerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.Property<string>("Sig")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StopDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TreatmentId")
                        .HasColumnType("text");

                    b.Property<string>("TreatmentName")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("WrittenDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WrittenQuantity")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisId");

                    b.HasIndex("DoseScheduleId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PractitionerId");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("DiagnosisEncounter", b =>
                {
                    b.Property<Guid>("DiagnosesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EncountersId")
                        .HasColumnType("uuid");

                    b.HasKey("DiagnosesId", "EncountersId");

                    b.HasIndex("EncountersId");

                    b.ToTable("DiagnosisEncounter");
                });

            modelBuilder.Entity("DataShapes.Model.Accreditation", b =>
                {
                    b.HasOne("DataShapes.Model.Location", null)
                        .WithMany("Accreditations")
                        .HasForeignKey("LocationId");
                });

            modelBuilder.Entity("DataShapes.Model.Address", b =>
                {
                    b.HasOne("DataShapes.Model.Location", null)
                        .WithMany("Addresses")
                        .HasForeignKey("LocationId");

                    b.HasOne("DataShapes.Model.Patient", null)
                        .WithMany("Addresses")
                        .HasForeignKey("PatientId");

                    b.HasOne("DataShapes.Model.Practitioner", null)
                        .WithMany("Addresses")
                        .HasForeignKey("PractitionerId");

                    b.HasOne("DataShapes.Model.Tenant", null)
                        .WithMany("Addresses")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataShapes.Model.Code", b =>
                {
                    b.HasOne("DataShapes.Model.Diagnosis", null)
                        .WithMany("Codes")
                        .HasForeignKey("DiagnosisId");

                    b.HasOne("DataShapes.Model.Encounter", null)
                        .WithMany("Codes")
                        .HasForeignKey("EncounterId");
                });

            modelBuilder.Entity("DataShapes.Model.Contact", b =>
                {
                    b.HasOne("DataShapes.Model.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("DataShapes.Model.Location", null)
                        .WithMany("Contacts")
                        .HasForeignKey("LocationId");

                    b.HasOne("DataShapes.Model.PersonName", "Name")
                        .WithMany()
                        .HasForeignKey("NameId");

                    b.HasOne("DataShapes.Model.Tenant", null)
                        .WithMany("Contacts")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Name");
                });

            modelBuilder.Entity("DataShapes.Model.ContactMethod", b =>
                {
                    b.HasOne("DataShapes.Model.Contact", null)
                        .WithMany("ContactMethods")
                        .HasForeignKey("ContactId");

                    b.HasOne("DataShapes.Model.Email", "Email")
                        .WithMany()
                        .HasForeignKey("EmailId");

                    b.HasOne("DataShapes.Model.Location", null)
                        .WithMany("ContactMethods")
                        .HasForeignKey("LocationId");

                    b.HasOne("DataShapes.Model.Patient", null)
                        .WithMany("ContactMethods")
                        .HasForeignKey("PatientId");

                    b.HasOne("DataShapes.Model.Phone", "Phone")
                        .WithMany()
                        .HasForeignKey("PhoneId");

                    b.HasOne("DataShapes.Model.Practitioner", null)
                        .WithMany("ContactMethods")
                        .HasForeignKey("PractitionerId");

                    b.HasOne("DataShapes.Model.Tenant", null)
                        .WithMany("ContactMethods")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("DataShapes.Model.Diagnosis", b =>
                {
                    b.HasOne("DataShapes.Model.Patient", "Patient")
                        .WithMany("Diagnoses")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DataShapes.Model.DoseDay", b =>
                {
                    b.HasOne("DataShapes.Model.DoseSchedule", null)
                        .WithMany("DoseDays")
                        .HasForeignKey("DoseScheduleId");

                    b.HasOne("DataShapes.Model.Treatment", null)
                        .WithMany("DoseDays")
                        .HasForeignKey("TreatmentId");
                });

            modelBuilder.Entity("DataShapes.Model.DoseEvent", b =>
                {
                    b.HasOne("DataShapes.Model.DoseDay", null)
                        .WithMany("DoseEvents")
                        .HasForeignKey("DoseDayId");

                    b.HasOne("DataShapes.Model.DoseSchedule", null)
                        .WithMany("DailyDoses")
                        .HasForeignKey("DoseScheduleId");
                });

            modelBuilder.Entity("DataShapes.Model.Encounter", b =>
                {
                    b.HasOne("DataShapes.Model.Prescription", "Prescription")
                        .WithMany()
                        .HasForeignKey("PrescriptionId");

                    b.HasOne("DataShapes.Model.Treatment", "Treatment")
                        .WithMany()
                        .HasForeignKey("TreatmentId");

                    b.Navigation("Prescription");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("DataShapes.Model.Identifier", b =>
                {
                    b.HasOne("DataShapes.Model.Patient", null)
                        .WithMany("HL7Identifiers")
                        .HasForeignKey("PatientId");

                    b.HasOne("DataShapes.Model.Practitioner", null)
                        .WithMany("FhirIdentifiers")
                        .HasForeignKey("PractitionerId");
                });

            modelBuilder.Entity("DataShapes.Model.Location", b =>
                {
                    b.HasOne("DataShapes.Model.Diagnosis", null)
                        .WithMany("Locations")
                        .HasForeignKey("DiagnosisId");

                    b.HasOne("DataShapes.Model.Encounter", null)
                        .WithMany("Locations")
                        .HasForeignKey("EncounterId");

                    b.HasOne("DataShapes.Model.Patient", null)
                        .WithMany("Locations")
                        .HasForeignKey("PatientId");

                    b.HasOne("DataShapes.Model.Practitioner", null)
                        .WithMany("Locations")
                        .HasForeignKey("PractitionerId");
                });

            modelBuilder.Entity("DataShapes.Model.Note", b =>
                {
                    b.HasOne("DataShapes.Model.Diagnosis", null)
                        .WithMany("Notes")
                        .HasForeignKey("DiagnosisId");
                });

            modelBuilder.Entity("DataShapes.Model.Observation", b =>
                {
                    b.HasOne("DataShapes.Model.Diagnosis", null)
                        .WithMany("Observations")
                        .HasForeignKey("DiagnosisId");

                    b.HasOne("DataShapes.Model.Encounter", null)
                        .WithMany("Observations")
                        .HasForeignKey("EncounterId");

                    b.HasOne("DataShapes.Model.Patient", null)
                        .WithMany("Observations")
                        .HasForeignKey("PatientId");
                });

            modelBuilder.Entity("DataShapes.Model.ObservationItem", b =>
                {
                    b.HasOne("DataShapes.Model.Code", "BodySite")
                        .WithMany()
                        .HasForeignKey("BodySiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataShapes.Model.Code", "Code")
                        .WithMany()
                        .HasForeignKey("CodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataShapes.Model.Code", "Method")
                        .WithMany()
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataShapes.Model.Observation", null)
                        .WithMany("Items")
                        .HasForeignKey("ObservationId");

                    b.HasOne("DataShapes.Model.Specimen", "Specimen")
                        .WithMany()
                        .HasForeignKey("SpecimenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodySite");

                    b.Navigation("Code");

                    b.Navigation("Method");

                    b.Navigation("Specimen");
                });

            modelBuilder.Entity("DataShapes.Model.Patient", b =>
                {
                    b.HasOne("DataShapes.Model.Encounter", null)
                        .WithMany("Patients")
                        .HasForeignKey("EncounterId");

                    b.HasOne("DataShapes.Model.PersonName", "Name")
                        .WithMany()
                        .HasForeignKey("NameId");

                    b.HasOne("DataShapes.Model.PatientCare", "PatientCare")
                        .WithMany()
                        .HasForeignKey("PatientCareId");

                    b.Navigation("Name");

                    b.Navigation("PatientCare");
                });

            modelBuilder.Entity("DataShapes.Model.PatientPractitioner", b =>
                {
                    b.HasOne("DataShapes.Model.Patient", null)
                        .WithMany("Practitioners")
                        .HasForeignKey("PatientId");

                    b.HasOne("DataShapes.Model.Practitioner", "Practitioner")
                        .WithMany()
                        .HasForeignKey("PractitionerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Practitioner");
                });

            modelBuilder.Entity("DataShapes.Model.PaymentMethod", b =>
                {
                    b.HasOne("DataShapes.Model.Tenant", null)
                        .WithMany("PaymentMethods")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataShapes.Model.PersonName", b =>
                {
                    b.HasOne("DataShapes.Model.Practitioner", null)
                        .WithMany("Name")
                        .HasForeignKey("PractitionerId");
                });

            modelBuilder.Entity("DataShapes.Model.Practitioner", b =>
                {
                    b.HasOne("DataShapes.Model.Diagnosis", null)
                        .WithMany("Practitioners")
                        .HasForeignKey("DiagnosisId");

                    b.HasOne("DataShapes.Model.Encounter", null)
                        .WithMany("Practitioners")
                        .HasForeignKey("EncounterId");

                    b.HasOne("DataShapes.Model.Encounter", null)
                        .WithMany("ReferringPractitioners")
                        .HasForeignKey("EncounterId1");
                });

            modelBuilder.Entity("DataShapes.Model.Prescription", b =>
                {
                    b.HasOne("DataShapes.Model.Diagnosis", "Diagnosis")
                        .WithMany("Prescriptions")
                        .HasForeignKey("DiagnosisId");

                    b.HasOne("DataShapes.Model.DoseSchedule", "DoseSchedule")
                        .WithMany()
                        .HasForeignKey("DoseScheduleId");

                    b.HasOne("DataShapes.Model.Location", "FillingPharmacy")
                        .WithMany()
                        .HasForeignKey("FillingPharmacyId");

                    b.HasOne("DataShapes.Model.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId");

                    b.HasOne("DataShapes.Model.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientId");

                    b.HasOne("DataShapes.Model.Practitioner", "Practitioner")
                        .WithMany()
                        .HasForeignKey("PractitionerId");

                    b.Navigation("Diagnosis");

                    b.Navigation("DoseSchedule");

                    b.Navigation("FillingPharmacy");

                    b.Navigation("Medication");

                    b.Navigation("Patient");

                    b.Navigation("Practitioner");
                });

            modelBuilder.Entity("DataShapes.Model.Specimen", b =>
                {
                    b.HasOne("DataShapes.Model.Code", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId");

                    b.HasOne("DataShapes.Model.Code", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("DataShapes.Model.Code", "SpecimenType")
                        .WithMany()
                        .HasForeignKey("SpecimenTypeId");

                    b.Navigation("Feature");

                    b.Navigation("Role");

                    b.Navigation("SpecimenType");
                });

            modelBuilder.Entity("DataShapes.Model.SpokenLanguage", b =>
                {
                    b.HasOne("DataShapes.Model.Patient", null)
                        .WithMany("Languages")
                        .HasForeignKey("PatientId");
                });

            modelBuilder.Entity("DataShapes.Model.Treatment", b =>
                {
                    b.HasOne("DataShapes.Model.Diagnosis", "Diagnosis")
                        .WithMany("Treatments")
                        .HasForeignKey("DiagnosisId");

                    b.HasOne("DataShapes.Model.DoseSchedule", "DoseSchedule")
                        .WithMany()
                        .HasForeignKey("DoseScheduleId");

                    b.HasOne("DataShapes.Model.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("DataShapes.Model.Patient", "Patient")
                        .WithMany("Treatments")
                        .HasForeignKey("PatientId");

                    b.HasOne("DataShapes.Model.Practitioner", "Practitioner")
                        .WithMany()
                        .HasForeignKey("PractitionerId");

                    b.Navigation("Diagnosis");

                    b.Navigation("DoseSchedule");

                    b.Navigation("Location");

                    b.Navigation("Patient");

                    b.Navigation("Practitioner");
                });

            modelBuilder.Entity("DiagnosisEncounter", b =>
                {
                    b.HasOne("DataShapes.Model.Diagnosis", null)
                        .WithMany()
                        .HasForeignKey("DiagnosesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataShapes.Model.Encounter", null)
                        .WithMany()
                        .HasForeignKey("EncountersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataShapes.Model.Contact", b =>
                {
                    b.Navigation("ContactMethods");
                });

            modelBuilder.Entity("DataShapes.Model.Diagnosis", b =>
                {
                    b.Navigation("Codes");

                    b.Navigation("Locations");

                    b.Navigation("Notes");

                    b.Navigation("Observations");

                    b.Navigation("Practitioners");

                    b.Navigation("Prescriptions");

                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("DataShapes.Model.DoseDay", b =>
                {
                    b.Navigation("DoseEvents");
                });

            modelBuilder.Entity("DataShapes.Model.DoseSchedule", b =>
                {
                    b.Navigation("DailyDoses");

                    b.Navigation("DoseDays");
                });

            modelBuilder.Entity("DataShapes.Model.Encounter", b =>
                {
                    b.Navigation("Codes");

                    b.Navigation("Locations");

                    b.Navigation("Observations");

                    b.Navigation("Patients");

                    b.Navigation("Practitioners");

                    b.Navigation("ReferringPractitioners");
                });

            modelBuilder.Entity("DataShapes.Model.Location", b =>
                {
                    b.Navigation("Accreditations");

                    b.Navigation("Addresses");

                    b.Navigation("ContactMethods");

                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("DataShapes.Model.Observation", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DataShapes.Model.Patient", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("ContactMethods");

                    b.Navigation("Diagnoses");

                    b.Navigation("HL7Identifiers");

                    b.Navigation("Languages");

                    b.Navigation("Locations");

                    b.Navigation("Observations");

                    b.Navigation("Practitioners");

                    b.Navigation("Prescriptions");

                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("DataShapes.Model.Practitioner", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("ContactMethods");

                    b.Navigation("FhirIdentifiers");

                    b.Navigation("Locations");

                    b.Navigation("Name");
                });

            modelBuilder.Entity("DataShapes.Model.Tenant", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("ContactMethods");

                    b.Navigation("Contacts");

                    b.Navigation("PaymentMethods");
                });

            modelBuilder.Entity("DataShapes.Model.Treatment", b =>
                {
                    b.Navigation("DoseDays");
                });
#pragma warning restore 612, 618
        }
    }
}
