version: '3.8'

services:      
  PrimaryConsumerApi:
    environment:
    - DOTNET_RUNNING_IN_DOCKER_CONTAINER=true
    
    image: ${DOCKER_REGISTRY-}primary-consumer-api
    restart: always
    ports: 
      - "5001:80"
    build:
      context: .
      dockerfile: src/PrimaryControllers/DebugDockerfile
    depends_on:
      - postgres
    networks:
      - backend-network

  postgres:
    image: pjenney58/palisaiddb:latest
    restart: always
    ports:
      - 5432:5432
    deploy:
      endpoint_mode: vip
      labels:
        com.example.description: "This label will appear on the service"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pgpassword
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  data: