version: '3.8'

services:      
  PrimaryConsumerApi:
    container_name: api-palisaid-consumer
    environment:
    - DOTNET_RUNNING_IN_DOCKER_CONTAINER=true
    
    image: ${DOCKER_REGISTRY-}primary-consumer-api
    restart: always
    ports: 
      - "5001:80"
    build:
      context: .
      dockerfile: src/PrimaryControllers/DebugDockerfile
    
    networks:
      - backend-network

  postgres:
    image: postgres:15.5-bullseye
    container_name: db-postgres-all
    restart: always
    ports:
      - 5432:5432

    deploy:
      endpoint_mode: vip
      labels:
        com.example.description: "This label will appear on the service"

    volumes:
      - data:/var/lib/postgresql/data
#      - ~/.postgres-data:/mnt/postgres-data
#      - ~/.postgres-data:/root/.gnupg
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpassword

    networks:
      - backend-network
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: pete.jenney@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  data: