version: '3.8'
# cell IP: 172.58.229.225
# public IP: 38.7.155.219
# LAN IP:  192.168.86.241 
services: 
    rabbitmq:
        image: bitnami/rabbitmq:latest
        container_name: rabbitmq
        restart: always
        networks:
        - backend-network
        ports:
        - 5672:5672
        - 15672:15672
        environment:
            RABBITMQ_USERNAME: palisaid
            RABBITMQ_PASSWORD: palisaid
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_MANAGER_PORT_NUMBER: 15672
            RABBITMQ_NODE_PORT_NUMBER: 5672
            RABBITMQ_NODE_NAME: rabbit@rabbitmq
            RABBITMQ_USE_LONGNAME: "true"
            RABBITMQ_CLUSTER_NODE_TYPE: ram

#  postgres:
  #  image: postgres:15.5-bullseye
  #      image: pjenney58/palisaiddb:latest
  #      container_name: db-postgres-all
  #      restart: always
  #      ports:
  #      - 5432:5432

  #      deploy:
  #          endpoint_mode: vip
  #      labels:
  #          com.example.description: "This label will appear on the service"

  #      volumes:
  #      - data:/var/lib/postgresql/data
  #      - ~/.postgres-data:/mnt/configuration-data
  #      - ~/.postgres-data:/root/.gnupg
  #      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  #      environment:
  #          POSTGRES_USER: postgres
   #         POSTGRES_PASSWORD: pgpassword
  
   #     networks:
   #     - backend-network
 
    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
  #      depends_on:
  #      - postgres
        environment:
            PGADMIN_DEFAULT_EMAIL: pete.jenney@gmail.com
            PGADMIN_DEFAULT_PASSWORD: postgres
        ports:
        - "5050:80"
        networks:
        - backend-network

    GatewayController:
        container_name: gatewayapi
        environment:
            - DOTNET_RUNNING_IN_DOCKER_CONTAINER=false
        image: pjenney58/gatewayapi
        restart: always
        ports: 
        - "5080:80"
        - "5081:443"
        build:
            context: .
            dockerfile: src/PrimaryControllers/Dockerfile
        networks:
        - backend-network

    CollectorController:
        container_name: collectorapi
        environment:
            - DOTNET_RUNNING_IN_DOCKER_CONTAINER=true
        image: pjenney58/collectorapi
        restart: always
        ports: 
        - "5001:80"
        build:
            context: .
            dockerfile: src/Collectors/CollectorsController/Dockerfile
        networks:
        - backend-network

    Fhir4Collector:
        container_name: fhir4Collector
        environment:
        - DOTNET_RUNNING_IN_DOCKER_CONTAINER=true
    
        image: pjenney58/fhir4collector
        restart: always
        ports: 
        - "5002:80"
        build:
            context: .
            dockerfile: src/Collectors/Fhir4Collector/Dockerfile
        networks:
        - backend-network


#    web:
#        image: nginx
#        volumes:
#            - ./templates:/etc/nginx/templates
#        ports:
#            - "80:80"
#            - "443:443" 
#        environment:
#        - NGINX_HOST=registry.sanddriftsoft.com
#        - NGINX_PORT=80
#        networks:
#        - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  data: