// <auto-generated />
using Hl7Harmonizer.MetaTypes.Model;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace Hl7Harmonizer.Repository.Migrations
{
    [DbContext(typeof(NpgDbContext))]
    partial class NpgDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.DoseDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DoseScheduleEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DoseScheduleOwnerID")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ThisDoseDay")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TreatmentEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TreatmentOwnerID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DoseScheduleEntityID", "DoseScheduleOwnerID");

                    b.HasIndex("TreatmentEntityID", "TreatmentOwnerID");

                    b.ToTable("DoseDays");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.DoseEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DoseDayId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DoseScheduleEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DoseScheduleOwnerID")
                        .HasColumnType("uuid");

                    b.Property<string>("Instruction")
                        .HasColumnType("text");

                    b.Property<decimal>("MaxmumCount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinmumCountOrDefault")
                        .HasColumnType("numeric");

                    b.Property<string>("Observation")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("DoseDayId");

                    b.HasIndex("DoseScheduleEntityID", "DoseScheduleOwnerID");

                    b.ToTable("DoseEvents");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Identifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IdSource")
                        .HasColumnType("text");

                    b.Property<string>("IdType")
                        .HasColumnType("text");

                    b.Property<string>("IdUse")
                        .HasColumnType("text");

                    b.Property<string>("IdValue")
                        .HasColumnType("text");

                    b.Property<Guid?>("PatientEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientOwnerID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PractitionerEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PractitionerOwnerID")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StopDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PatientEntityID", "PatientOwnerID");

                    b.HasIndex("PractitionerEntityID", "PractitionerOwnerID");

                    b.ToTable("Identifiers");
                });

            modelBuilder.Entity("Hl7Harmonizer.Support.Model.Entity", b =>
                {
                    b.Property<Guid?>("EntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OwnerID")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetaType")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetaType")
                        .HasColumnType("text");

                    b.Property<string>("Partition")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("EntityID", "OwnerID");

                    b.ToTable("Entity");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Address", b =>
                {
                    b.HasBaseType("Hl7Harmonizer.Support.Model.Entity");

                    b.Property<string>("Address1")
                        .HasColumnType("text");

                    b.Property<string>("Address2")
                        .HasColumnType("text");

                    b.Property<string>("Address3")
                        .HasColumnType("text");

                    b.Property<int>("AddressType")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<Guid?>("CustomerEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerOwnerID")
                        .HasColumnType("uuid");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<string>("HL7AddressCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("LocationEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocationOwnerID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientOwnerID")
                        .HasColumnType("uuid");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<Guid?>("PractitionerEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PractitionerOwnerID")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StopDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Use")
                        .HasColumnType("integer");

                    b.HasIndex("CustomerEntityID", "CustomerOwnerID");

                    b.HasIndex("LocationEntityID", "LocationOwnerID");

                    b.HasIndex("PatientEntityID", "PatientOwnerID");

                    b.HasIndex("PractitionerEntityID", "PractitionerOwnerID");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Allergy", b =>
                {
                    b.HasBaseType("Hl7Harmonizer.Support.Model.Entity");

                    b.Property<string>("Icd10Code")
                        .HasColumnType("text");

                    b.Property<string>("Icd10LongDescription")
                        .HasColumnType("text");

                    b.Property<string>("Icd10ShortDescription")
                        .HasColumnType("text");

                    b.Property<string>("SNOMEDUri")
                        .HasColumnType("text");

                    b.Property<string>("SNOWMEDCode")
                        .HasColumnType("text");

                    b.Property<string>("SNOWMEDDescription")
                        .HasColumnType("text");

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Encounter", b =>
                {
                    b.HasBaseType("Hl7Harmonizer.Support.Model.Entity");

                    b.Property<int>("EncounterStatus")
                        .HasColumnType("integer");

                    b.Property<int>("EncounterType")
                        .HasColumnType("integer");

                    b.Property<List<Guid>>("Codes")
                        .HasColumnType("uuid[]");

                    b.Property<List<Guid>>("Diagnoses")
                        .HasColumnType("uuid[]");

                    b.Property<Guid?>("DiagnosisEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DiagnosisOwnerID")
                        .HasColumnType("uuid");

                    b.Property<List<Guid>>("Locations")
                        .HasColumnType("uuid[]");

                    b.Property<List<Guid>>("Observations")
                        .HasColumnType("uuid[]");

                    b.Property<List<Guid>>("Patients")
                        .HasColumnType("uuid[]");

                    b.Property<List<Guid>>("Practitioners")
                        .HasColumnType("uuid[]");

                    b.Property<Guid?>("Prescription")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StopDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("Treatment")
                        .HasColumnType("uuid");

                    b.HasIndex("DiagnosisEntityID", "DiagnosisOwnerID");

                    b.ToTable("CareEvents");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Code", b =>
                {
                    b.HasBaseType("Hl7Harmonizer.Support.Model.Entity");

                    b.Property<int>("CodingSystem")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("DiagnosisEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DiagnosisOwnerID")
                        .HasColumnType("uuid");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasIndex("DiagnosisEntityID", "DiagnosisOwnerID");

                    b.ToTable("Codes");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Contact", b =>
                {
                    b.HasBaseType("Hl7Harmonizer.Support.Model.Entity");

                    b.Property<Guid?>("AddressEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AddressOwnerID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerOwnerID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocationEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocationOwnerID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NameEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NameOwnerID")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasIndex("AddressEntityID", "AddressOwnerID");

                    b.HasIndex("CustomerEntityID", "CustomerOwnerID");

                    b.HasIndex("LocationEntityID", "LocationOwnerID");

                    b.HasIndex("NameEntityID", "NameOwnerID");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.ContactMethod", b =>
                {
                    b.HasBaseType("Hl7Harmonizer.Support.Model.Entity");

                    b.Property<Guid?>("ContactEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContactOwnerID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomerOwnerID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EmailEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EmailOwnerID")
                        .HasColumnType("uuid");

                    b.Property<string>("IM")
                        .HasColumnType("text");

                    b.Property<Guid?>("LocationEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocationOwnerID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientOwnerID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PhoneEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PhoneOwnerID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PractitionerEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PractitionerOwnerID")
                        .HasColumnType("uuid");

                    b.Property<Dictionary<string, string>>("SocialMedia")
                        .IsRequired()
                        .HasColumnType("hstore");

                    b.HasIndex("ContactEntityID", "ContactOwnerID");

                    b.HasIndex("CustomerEntityID", "CustomerOwnerID");

                    b.HasIndex("EmailEntityID", "EmailOwnerID");

                    b.HasIndex("LocationEntityID", "LocationOwnerID");

                    b.HasIndex("PatientEntityID", "PatientOwnerID");

                    b.HasIndex("PhoneEntityID", "PhoneOwnerID");

                    b.HasIndex("PractitionerEntityID", "PractitionerOwnerID");

                    b.ToTable("ContactMethods");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Customer", b =>
                {
                    b.HasBaseType("Hl7Harmonizer.Support.Model.Entity");

                    b.Property<string>("AdminName")
                        .HasColumnType("text");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Group")
                        .HasColumnType("text");

                    b.Property<string>("ManagerName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DisposableList<PaymentMethod>>("PaymentMethods")
                        .HasColumnType("jsonb");

                    b.Property<string>("Team")
                        .HasColumnType("text");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Diagnosis", b =>
                {
                    b.HasBaseType("Hl7Harmonizer.Support.Model.Entity");

                    b.Property<Guid>("CurrentLocation")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientOwnerID")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StopDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasIndex("PatientEntityID", "PatientOwnerID");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.DoseSchedule", b =>
                {
                    b.HasBaseType("Hl7Harmonizer.Support.Model.Entity");

                    b.Property<int>("AlternatingRepeatDays")
                        .HasColumnType("integer");

                    b.Property<string>("DoseRepeatPattern")
                        .HasColumnType("text");

                    b.Property<string>("DoseScheduleName")
                        .HasColumnType("text");

                    b.Property<bool>("IsPrn")
                        .HasColumnType("boolean");

                    b.ToTable("DoseSchedules");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Email", b =>
                {
                    b.HasBaseType("Hl7Harmonizer.Support.Model.Entity");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Location", b =>
                {
                    b.HasBaseType("Hl7Harmonizer.Support.Model.Entity");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("DiagnosisEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DiagnosisOwnerID")
                        .HasColumnType("uuid");

                    b.Property<Dictionary<string, string>>("Licenses")
                        .HasColumnType("jsonb");

                    b.Property<int?>("LocationType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("PatientEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientOwnerID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PractitionerEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PractitionerOwnerID")
                        .HasColumnType("uuid");

                    b.HasIndex("DiagnosisEntityID", "DiagnosisOwnerID");

                    b.HasIndex("PatientEntityID", "PatientOwnerID");

                    b.HasIndex("PractitionerEntityID", "PractitionerOwnerID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Medication", b =>
                {
                    b.HasBaseType("Hl7Harmonizer.Support.Model.Entity");

                    b.Property<string>("BrandName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ExpireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Form")
                        .HasColumnType("text");

                    b.Property<string>("GenericName")
                        .HasColumnType("text");

                    b.Property<bool>("IsGeneric")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOtc")
                        .HasColumnType("boolean");

                    b.Property<string>("LongVisualDescription")
                        .HasColumnType("text");

                    b.Property<string>("LotId")
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("MedicationCode")
                        .HasColumnType("text");

                    b.Property<Guid?>("MedicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Route")
                        .HasColumnType("text");

                    b.Property<string>("Schedule")
                        .HasColumnType("text");

                    b.Property<string>("ShortVisualDescription")
                        .HasColumnType("text");

                    b.Property<string>("SpecialInstructions")
                        .HasColumnType("text");

                    b.Property<string>("Strength")
                        .HasColumnType("text");

                    b.Property<string>("StrengthUnits")
                        .HasColumnType("text");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Note", b =>
                {
                    b.HasBaseType("Hl7Harmonizer.Support.Model.Entity");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<Guid?>("DiagnosisEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DiagnosisOwnerID")
                        .HasColumnType("uuid");

                    b.Property<string>("NoteId")
                        .HasColumnType("text");

                    b.Property<int>("NoteType")
                        .HasColumnType("integer");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasIndex("DiagnosisEntityID", "DiagnosisOwnerID");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Observation", b =>
                {
                    b.HasBaseType("Hl7Harmonizer.Support.Model.Entity");

                    b.Property<Guid?>("DiagnosisEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DiagnosisOwnerID")
                        .HasColumnType("uuid");

                    b.Property<List<KeyValuePair<ObservationType, ObservationItem>>>("Items")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientOwnerID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PractitionerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StopDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasIndex("DiagnosisEntityID", "DiagnosisOwnerID");

                    b.HasIndex("PatientEntityID", "PatientOwnerID");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.ObservationItem", b =>
                {
                    b.HasBaseType("Hl7Harmonizer.Support.Model.Entity");

                    b.Property<Guid>("CodeEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CodeOwnerID")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("ObservationReference")
                        .HasColumnType("uuid");

                    b.Property<int?>("ObservationType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasIndex("CodeEntityID", "CodeOwnerID");

                    b.ToTable("ObservationsItem");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Patient", b =>
                {
                    b.HasBaseType("Hl7Harmonizer.Support.Model.Entity");

                    b.Property<DateTimeOffset>("AdmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AlternatePatientIdentifier")
                        .HasColumnType("text");

                    b.Property<string>("Bed")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DeceasedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DischargeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Floor")
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeceased")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("NameEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NameOwnerID")
                        .HasColumnType("uuid");

                    b.Property<string>("NursingStation")
                        .HasColumnType("text");

                    b.Property<Guid?>("PatientCareEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientCareOwnerID")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea");

                    b.Property<string>("PrimaryLanguage")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryPatientIdentifier")
                        .HasColumnType("text");

                    b.Property<string>("Room")
                        .HasColumnType("text");

                    b.Property<bool>("UsePatientInfo")
                        .HasColumnType("boolean");

                    b.HasIndex("NameEntityID", "NameOwnerID");

                    b.HasIndex("PatientCareEntityID", "PatientCareOwnerID");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.PatientCare", b =>
                {
                    b.HasBaseType("Hl7Harmonizer.Support.Model.Entity");

                    b.Property<string>("AlternateGroupId")
                        .HasColumnType("text");

                    b.Property<string>("AlternateInsuranceName")
                        .HasColumnType("text");

                    b.Property<string>("AlternatePolicyId")
                        .HasColumnType("text");

                    b.Property<string>("CareId")
                        .HasColumnType("text");

                    b.Property<byte>("CodeStatus")
                        .HasColumnType("smallint");

                    b.Property<byte>("CodeStatusLimitedCodeOptions")
                        .HasColumnType("smallint");

                    b.Property<string>("HipaaChangeAuthorLogin")
                        .HasColumnType("text");

                    b.Property<DateTime>("HipaaChangeDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("HipaaDataTransmitAuthentication")
                        .HasColumnType("boolean");

                    b.Property<string>("MedicaidId")
                        .HasColumnType("text");

                    b.Property<string>("MedicareId")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryGroupId")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryInsuranceName")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryPolicyId")
                        .HasColumnType("text");

                    b.Property<string>("SocialSecurityNumber")
                        .HasColumnType("text");

                    b.ToTable("PatientCares");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.PatientPractitioner", b =>
                {
                    b.HasBaseType("Hl7Harmonizer.Support.Model.Entity");

                    b.Property<Guid?>("PatientEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientOwnerID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PractitionerEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PractitionerOwnerID")
                        .HasColumnType("uuid");

                    b.Property<int>("Relationship")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StopDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasIndex("PatientEntityID", "PatientOwnerID");

                    b.HasIndex("PractitionerEntityID", "PractitionerOwnerID");

                    b.ToTable("PatientPractitioners");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.PersonName", b =>
                {
                    b.HasBaseType("Hl7Harmonizer.Support.Model.Entity");

                    b.Property<string>("FamilyName")
                        .HasColumnType("text");

                    b.Property<List<string>>("GivenName")
                        .HasColumnType("text[]");

                    b.Property<string>("KnownByName")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<Guid?>("PractitionerEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PractitionerOwnerID")
                        .HasColumnType("uuid");

                    b.Property<List<string>>("Prefix")
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StopDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("Suffix")
                        .HasColumnType("text[]");

                    b.HasIndex("PractitionerEntityID", "PractitionerOwnerID");

                    b.ToTable("PersonNames");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Phone", b =>
                {
                    b.HasBaseType("Hl7Harmonizer.Support.Model.Entity");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<string>("Extension")
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Practitioner", b =>
                {
                    b.HasBaseType("Hl7Harmonizer.Support.Model.Entity");

                    b.Property<DateTimeOffset>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DeceasedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DiagnosisEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DiagnosisOwnerID")
                        .HasColumnType("uuid");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeceased")
                        .HasColumnType("boolean");

                    b.Property<List<KeyValuePair<string, string>>>("LicensesAndQualifications")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PractitionerIdentifier")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryLanguage")
                        .HasColumnType("text");

                    b.HasIndex("DiagnosisEntityID", "DiagnosisOwnerID");

                    b.ToTable("Practitioners");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Prescription", b =>
                {
                    b.HasBaseType("Hl7Harmonizer.Support.Model.Entity");

                    b.Property<int>("ScripCatagories")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DcDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DiagnosisEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DiagnosisOwnerID")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DispenseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DoNotPerform")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("DoseScheduleEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DoseScheduleOwnerID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FillingPharmacyEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FillingPharmacyOwnerID")
                        .HasColumnType("uuid");

                    b.Property<int>("ScripIntent")
                        .HasColumnType("integer");

                    b.Property<bool>("IsIsolated")
                        .HasColumnType("boolean");

                    b.Property<int>("MaximumRefills")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MedicationEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MedicationOwnerID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientOwnerID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PractitionerEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PractitionerOwnerID")
                        .HasColumnType("uuid");

                    b.Property<string>("PrescriptionName")
                        .HasColumnType("text");

                    b.Property<string>("PriorPrescriptionName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RefillRequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RefillRequestType")
                        .HasColumnType("integer");

                    b.Property<int>("RemainingRefills")
                        .HasColumnType("integer");

                    b.Property<int>("RxType")
                        .HasColumnType("integer");

                    b.Property<int>("ScripStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Sig")
                        .HasColumnType("text");

                    b.Property<List<string>>("SpecialInstructions")
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StatusReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StopDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("WrittenDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WrittenQuantity")
                        .HasColumnType("numeric");

                    b.HasIndex("DiagnosisEntityID", "DiagnosisOwnerID");

                    b.HasIndex("DoseScheduleEntityID", "DoseScheduleOwnerID");

                    b.HasIndex("FillingPharmacyEntityID", "FillingPharmacyOwnerID");

                    b.HasIndex("MedicationEntityID", "MedicationOwnerID");

                    b.HasIndex("PatientEntityID", "PatientOwnerID");

                    b.HasIndex("PractitionerEntityID", "PractitionerOwnerID");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Treatment", b =>
                {
                    b.HasBaseType("Hl7Harmonizer.Support.Model.Entity");

                    b.Property<DateTimeOffset>("DcDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DiagnosisEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DiagnosisOwnerID")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DispenseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DoseScheduleEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DoseScheduleOwnerID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocationEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocationOwnerID")
                        .HasColumnType("uuid");

                    b.Property<string>("LongDescription")
                        .HasColumnType("text");

                    b.Property<Guid>("PatientEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientOwnerID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PractitionerEntityID")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PractitionerOwnerID")
                        .HasColumnType("uuid");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.Property<string>("Sig")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StopDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TreatmentId")
                        .HasColumnType("text");

                    b.Property<string>("TreatmentName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("WrittenDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WrittenQuantity")
                        .HasColumnType("numeric");

                    b.HasIndex("DiagnosisEntityID", "DiagnosisOwnerID");

                    b.HasIndex("DoseScheduleEntityID", "DoseScheduleOwnerID");

                    b.HasIndex("LocationEntityID", "LocationOwnerID");

                    b.HasIndex("PatientEntityID", "PatientOwnerID");

                    b.HasIndex("PractitionerEntityID", "PractitionerOwnerID");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.DoseDay", b =>
                {
                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.DoseSchedule", null)
                        .WithMany("DoseDays")
                        .HasForeignKey("DoseScheduleEntityID", "DoseScheduleOwnerID");

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Treatment", null)
                        .WithMany("DoseDays")
                        .HasForeignKey("TreatmentEntityID", "TreatmentOwnerID");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.DoseEvent", b =>
                {
                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.DoseDay", null)
                        .WithMany("DoseEvents")
                        .HasForeignKey("DoseDayId");

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.DoseSchedule", null)
                        .WithMany("DailyDoses")
                        .HasForeignKey("DoseScheduleEntityID", "DoseScheduleOwnerID");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Identifier", b =>
                {
                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Patient", null)
                        .WithMany("FhirIdentifiers")
                        .HasForeignKey("PatientEntityID", "PatientOwnerID");

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Practitioner", null)
                        .WithMany("FhirIdentifiers")
                        .HasForeignKey("PractitionerEntityID", "PractitionerOwnerID");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Address", b =>
                {
                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Customer", null)
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerEntityID", "CustomerOwnerID");

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Location", null)
                        .WithMany("Addresses")
                        .HasForeignKey("LocationEntityID", "LocationOwnerID");

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Patient", null)
                        .WithMany("Addresses")
                        .HasForeignKey("PatientEntityID", "PatientOwnerID");

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Practitioner", null)
                        .WithMany("Addresses")
                        .HasForeignKey("PractitionerEntityID", "PractitionerOwnerID");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Encounter", b =>
                {
                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Diagnosis", null)
                        .WithMany("CareEvents")
                        .HasForeignKey("DiagnosisEntityID", "DiagnosisOwnerID");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Code", b =>
                {
                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Diagnosis", null)
                        .WithMany("Codes")
                        .HasForeignKey("DiagnosisEntityID", "DiagnosisOwnerID");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Contact", b =>
                {
                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressEntityID", "AddressOwnerID");

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Customer", null)
                        .WithMany("Contacts")
                        .HasForeignKey("CustomerEntityID", "CustomerOwnerID");

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Location", null)
                        .WithMany("Contacts")
                        .HasForeignKey("LocationEntityID", "LocationOwnerID");

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.PersonName", "Name")
                        .WithMany()
                        .HasForeignKey("NameEntityID", "NameOwnerID");

                    b.Navigation("Address");

                    b.Navigation("Name");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.ContactMethod", b =>
                {
                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Contact", null)
                        .WithMany("ContactMethods")
                        .HasForeignKey("ContactEntityID", "ContactOwnerID");

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Customer", null)
                        .WithMany("ContactMethods")
                        .HasForeignKey("CustomerEntityID", "CustomerOwnerID");

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Email", "Email")
                        .WithMany()
                        .HasForeignKey("EmailEntityID", "EmailOwnerID");

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Location", null)
                        .WithMany("ContactMethods")
                        .HasForeignKey("LocationEntityID", "LocationOwnerID");

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Patient", null)
                        .WithMany("ContactMethods")
                        .HasForeignKey("PatientEntityID", "PatientOwnerID");

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Phone", "Phone")
                        .WithMany()
                        .HasForeignKey("PhoneEntityID", "PhoneOwnerID");

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Practitioner", null)
                        .WithMany("ContactMethods")
                        .HasForeignKey("PractitionerEntityID", "PractitionerOwnerID");

                    b.Navigation("Email");

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Customer", b =>
                {
                    b.HasOne("Hl7Harmonizer.Support.Model.Entity", null)
                        .WithOne()
                        .HasForeignKey("Hl7Harmonizer.MetaTypes.Model.Customer", "EntityID", "OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Diagnosis", b =>
                {
                    b.HasOne("Hl7Harmonizer.Support.Model.Entity", null)
                        .WithOne()
                        .HasForeignKey("Hl7Harmonizer.MetaTypes.Model.Diagnosis", "EntityID", "OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Patient", "Patient")
                        .WithMany("Diagnoses")
                        .HasForeignKey("PatientEntityID", "PatientOwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.DoseSchedule", b =>
                {
                    b.HasOne("Hl7Harmonizer.Support.Model.Entity", null)
                        .WithOne()
                        .HasForeignKey("Hl7Harmonizer.MetaTypes.Model.DoseSchedule", "EntityID", "OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Email", b =>
                {
                    b.HasOne("Hl7Harmonizer.Support.Model.Entity", null)
                        .WithOne()
                        .HasForeignKey("Hl7Harmonizer.MetaTypes.Model.Email", "EntityID", "OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Location", b =>
                {
                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Diagnosis", null)
                        .WithMany("Locations")
                        .HasForeignKey("DiagnosisEntityID", "DiagnosisOwnerID");

                    b.HasOne("Hl7Harmonizer.Support.Model.Entity", null)
                        .WithOne()
                        .HasForeignKey("Hl7Harmonizer.MetaTypes.Model.Location", "EntityID", "OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Patient", null)
                        .WithMany("Locations")
                        .HasForeignKey("PatientEntityID", "PatientOwnerID");

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Practitioner", null)
                        .WithMany("Locations")
                        .HasForeignKey("PractitionerEntityID", "PractitionerOwnerID");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Medication", b =>
                {
                    b.HasOne("Hl7Harmonizer.Support.Model.Entity", null)
                        .WithOne()
                        .HasForeignKey("Hl7Harmonizer.MetaTypes.Model.Medication", "EntityID", "OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Note", b =>
                {
                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Diagnosis", null)
                        .WithMany("Notes")
                        .HasForeignKey("DiagnosisEntityID", "DiagnosisOwnerID");

                    b.HasOne("Hl7Harmonizer.Support.Model.Entity", null)
                        .WithOne()
                        .HasForeignKey("Hl7Harmonizer.MetaTypes.Model.Note", "EntityID", "OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Observation", b =>
                {
                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Diagnosis", null)
                        .WithMany("Observations")
                        .HasForeignKey("DiagnosisEntityID", "DiagnosisOwnerID");

                    b.HasOne("Hl7Harmonizer.Support.Model.Entity", null)
                        .WithOne()
                        .HasForeignKey("Hl7Harmonizer.MetaTypes.Model.Observation", "EntityID", "OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Patient", null)
                        .WithMany("Observations")
                        .HasForeignKey("PatientEntityID", "PatientOwnerID");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.ObservationItem", b =>
                {
                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Code", "Code")
                        .WithMany()
                        .HasForeignKey("CodeEntityID", "CodeOwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hl7Harmonizer.Support.Model.Entity", null)
                        .WithOne()
                        .HasForeignKey("Hl7Harmonizer.MetaTypes.Model.ObservationItem", "EntityID", "OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Code");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Patient", b =>
                {
                    b.HasOne("Hl7Harmonizer.Support.Model.Entity", null)
                        .WithOne()
                        .HasForeignKey("Hl7Harmonizer.MetaTypes.Model.Patient", "EntityID", "OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.PersonName", "Name")
                        .WithMany()
                        .HasForeignKey("NameEntityID", "NameOwnerID");

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.PatientCare", "PatientCare")
                        .WithMany()
                        .HasForeignKey("PatientCareEntityID", "PatientCareOwnerID");

                    b.Navigation("Name");

                    b.Navigation("PatientCare");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.PatientCare", b =>
                {
                    b.HasOne("Hl7Harmonizer.Support.Model.Entity", null)
                        .WithOne()
                        .HasForeignKey("Hl7Harmonizer.MetaTypes.Model.PatientCare", "EntityID", "OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.PatientPractitioner", b =>
                {
                    b.HasOne("Hl7Harmonizer.Support.Model.Entity", null)
                        .WithOne()
                        .HasForeignKey("Hl7Harmonizer.MetaTypes.Model.PatientPractitioner", "EntityID", "OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Patient", null)
                        .WithMany("Practitioners")
                        .HasForeignKey("PatientEntityID", "PatientOwnerID");

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Practitioner", "Practitioner")
                        .WithMany()
                        .HasForeignKey("PractitionerEntityID", "PractitionerOwnerID");

                    b.Navigation("Practitioner");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.PersonName", b =>
                {
                    b.HasOne("Hl7Harmonizer.Support.Model.Entity", null)
                        .WithOne()
                        .HasForeignKey("Hl7Harmonizer.MetaTypes.Model.PersonName", "EntityID", "OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Practitioner", null)
                        .WithMany("Name")
                        .HasForeignKey("PractitionerEntityID", "PractitionerOwnerID");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Phone", b =>
                {
                    b.HasOne("Hl7Harmonizer.Support.Model.Entity", null)
                        .WithOne()
                        .HasForeignKey("Hl7Harmonizer.MetaTypes.Model.Phone", "EntityID", "OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Practitioner", b =>
                {
                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Diagnosis", null)
                        .WithMany("Practitioners")
                        .HasForeignKey("DiagnosisEntityID", "DiagnosisOwnerID");

                    b.HasOne("Hl7Harmonizer.Support.Model.Entity", null)
                        .WithOne()
                        .HasForeignKey("Hl7Harmonizer.MetaTypes.Model.Practitioner", "EntityID", "OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Prescription", b =>
                {
                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Diagnosis", "Diagnosis")
                        .WithMany("Prescriptions")
                        .HasForeignKey("DiagnosisEntityID", "DiagnosisOwnerID");

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.DoseSchedule", "DoseSchedule")
                        .WithMany()
                        .HasForeignKey("DoseScheduleEntityID", "DoseScheduleOwnerID");

                    b.HasOne("Hl7Harmonizer.Support.Model.Entity", null)
                        .WithOne()
                        .HasForeignKey("Hl7Harmonizer.MetaTypes.Model.Prescription", "EntityID", "OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Location", "FillingPharmacy")
                        .WithMany()
                        .HasForeignKey("FillingPharmacyEntityID", "FillingPharmacyOwnerID");

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationEntityID", "MedicationOwnerID");

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientEntityID", "PatientOwnerID");

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Practitioner", "Practitioner")
                        .WithMany()
                        .HasForeignKey("PractitionerEntityID", "PractitionerOwnerID");

                    b.Navigation("Diagnosis");

                    b.Navigation("DoseSchedule");

                    b.Navigation("FillingPharmacy");

                    b.Navigation("Medication");

                    b.Navigation("Patient");

                    b.Navigation("Practitioner");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Treatment", b =>
                {
                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Diagnosis", "Diagnosis")
                        .WithMany("Treatments")
                        .HasForeignKey("DiagnosisEntityID", "DiagnosisOwnerID");

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.DoseSchedule", "DoseSchedule")
                        .WithMany()
                        .HasForeignKey("DoseScheduleEntityID", "DoseScheduleOwnerID");

                    b.HasOne("Hl7Harmonizer.Support.Model.Entity", null)
                        .WithOne()
                        .HasForeignKey("Hl7Harmonizer.MetaTypes.Model.Treatment", "EntityID", "OwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationEntityID", "LocationOwnerID");

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Patient", "Patient")
                        .WithMany("Treatments")
                        .HasForeignKey("PatientEntityID", "PatientOwnerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hl7Harmonizer.MetaTypes.Model.Practitioner", "Practitioner")
                        .WithMany()
                        .HasForeignKey("PractitionerEntityID", "PractitionerOwnerID");

                    b.Navigation("Diagnosis");

                    b.Navigation("DoseSchedule");

                    b.Navigation("Location");

                    b.Navigation("Patient");

                    b.Navigation("Practitioner");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.DoseDay", b =>
                {
                    b.Navigation("DoseEvents");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Contact", b =>
                {
                    b.Navigation("ContactMethods");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("ContactMethods");

                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Diagnosis", b =>
                {
                    b.Navigation("CareEvents");

                    b.Navigation("Codes");

                    b.Navigation("Locations");

                    b.Navigation("Notes");

                    b.Navigation("Observations");

                    b.Navigation("Practitioners");

                    b.Navigation("Prescriptions");

                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.DoseSchedule", b =>
                {
                    b.Navigation("DailyDoses");

                    b.Navigation("DoseDays");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Location", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("ContactMethods");

                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Patient", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("ContactMethods");

                    b.Navigation("Diagnoses");

                    b.Navigation("FhirIdentifiers");

                    b.Navigation("Locations");

                    b.Navigation("Observations");

                    b.Navigation("Practitioners");

                    b.Navigation("Prescriptions");

                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Practitioner", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("ContactMethods");

                    b.Navigation("FhirIdentifiers");

                    b.Navigation("Locations");

                    b.Navigation("Name");
                });

            modelBuilder.Entity("Hl7Harmonizer.MetaTypes.Model.Treatment", b =>
                {
                    b.Navigation("DoseDays");
                });
#pragma warning restore 612, 618
        }
    }
}
